AWSTemplateFormatVersion: 2010-09-09

Parameters:
  VpcId:
    Type: String
  PrivateSubnetsCidr:
    Type: String
  PrivateSubnets:
    Type: String
  PrivateRouteTable:
    Type: String
  PublicSubnets:
    Type: String

Resources:
  ECRDKRVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.ecr.dkr'
      VpcEndpointType: Interface
      SecurityGroupIds:
        - !GetAtt VPCEndpointSecurityGroup.GroupId
      PrivateDnsEnabled: true
      VpcId: !Ref VpcId
      SubnetIds: !Split [ ',', !Ref PrivateSubnets ]

  ECRAPIVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.ecr.api'
      VpcEndpointType: Interface
      SecurityGroupIds:
        - !GetAtt VPCEndpointSecurityGroup.GroupId
      PrivateDnsEnabled: true
      VpcId: !Ref VpcId
      SubnetIds: !Split [ ',', !Ref PrivateSubnets ]

  S3VPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.s3'
      VpcEndpointType: Gateway
      RouteTableIds:
        - !Ref PrivateRouteTable
      VpcId: !Ref VpcId

  CloudWatchVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.logs'
      VpcEndpointType: Interface
      SecurityGroupIds:
        - !GetAtt VPCEndpointSecurityGroup.GroupId
      PrivateDnsEnabled: true
      VpcId: !Ref VpcId
      SubnetIds: !Split [ ',', !Ref PrivateSubnets ]

  VPCEndpointSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for vpc endpoints
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - CidrIp: !Ref PrivateSubnetsCidr
          IpProtocol: tcp
          FromPort: 443
          ToPort: 443